version: '3.8'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=dynamodb
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_DEFAULT_REGION=us-east-1
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - ecatrom2000

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://localstack:4566"
    depends_on:
      - localstack
    networks:
      - ecatrom2000

  dynamodb-table:
    image: amazon/aws-cli:latest
    entrypoint: "/bin/sh -c \"aws dynamodb create-table --region us-east-1 --table-name $${DYNAMO_TABLE_NAME} --attribute-definitions AttributeName=key,AttributeType=S --key-schema AttributeName=key,KeyType=HASH --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1 --endpoint-url http://localstack:4566\""
    volumes:
      - ~/.aws:/root/.aws
    env_file:
      - .env.local
    networks:
      - ecatrom2000
    depends_on:
      - localstack
      - dynamodb-admin

networks:
  ecatrom2000:
    driver: bridge
